// <auto-generated />
namespace ClassAnalytics.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class messaging : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(messaging));
        
        string IMigrationMetadata.Id
        {
            get { return "201606151934442_messaging"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
